name: Publish CV

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Release latest CV
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Build CV
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: cv.tex
        working_directory: ./
        args: -xelatex -file-line-error -interaction=nonstopmode
        compiler: latexmk
        
    - name: Format current date
      id: format_date
      run: echo "::set-output name=date::$(date +"%B %d, %Y")"
    
    - name: Create new release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: CV as of ${{ steps.format_date.outputs.date }}
        draft: false
        prerelease: false

    - name: Add CV to latest release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cv.pdf
        asset_name: cv.pdf
        asset_content_type: application/pdf
